name = "dobby-zork"
main = "src/worker/index.mjs"
compatibility_date = "2024-09-09"
workers_dev = true
assets = { directory = "src/client" }
# Environment variables:
# - Use `wrangler secrets put `FIREWORKS_API_KEY` and `GEMINI_API_KEY` for adapters.

[env.preview]
workers_dev = true
[[env.preview.kv_namespaces]]
binding = "SESSIONS_KV"
preview_id = "a95d7baaf0af4e3586e303c316076dc1"

[env.production]
# Set a route if deploying to a zone (optional). Without routes, publish to workers.dev.
# routes = ["https://yourdomain.example/api/*"]
[[env.production.kv_namespaces]]
binding = "SESSIONS_KV"
id = "a95d7baaf0af4e3586e303c316076dc1"
